//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedETS2Packer.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Export {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Export() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdvancedETS2Packer.Languages.Export", typeof(Export).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning cache....
        /// </summary>
        internal static string dialog_Cleanup {
            get {
                return ResourceManager.GetString("dialog_Cleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying mod files....
        /// </summary>
        internal static string dialog_Copyiing {
            get {
                return ResourceManager.GetString("dialog_Copyiing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging non Steam version of mod....
        /// </summary>
        internal static string dialog_PackagingNonSteam {
            get {
                return ResourceManager.GetString("dialog_PackagingNonSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging Steam version of mod....
        /// </summary>
        internal static string dialog_PackagingSteam {
            get {
                return ResourceManager.GetString("dialog_PackagingSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in packing non-Steam version..
        /// </summary>
        internal static string ErrorInPackingNonSteam {
            get {
                return ResourceManager.GetString("ErrorInPackingNonSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder mentioned in the template does not exists!.
        /// </summary>
        internal static string FolderInTemplateNotExists {
            get {
                return ResourceManager.GetString("FolderInTemplateNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod manifest was not found, mod might not work properly..
        /// </summary>
        internal static string ManifestNotFound {
            get {
                return ResourceManager.GetString("ManifestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not found.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging....
        /// </summary>
        internal static string Packaging___ {
            get {
                return ResourceManager.GetString("Packaging...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing completed successfully!.
        /// </summary>
        internal static string PackingCompleted {
            get {
                return ResourceManager.GetString("PackingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing of mod {0} was completed successfully! For other informations, you can look into logfiles in the program folder..
        /// </summary>
        internal static string PackingCompleted2 {
            get {
                return ResourceManager.GetString("PackingCompleted2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing completed successfully!.
        /// </summary>
        internal static string PackingGroupCompleted {
            get {
                return ResourceManager.GetString("PackingGroupCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing of group of mods {0} was completed successfully! For other informations, you can look into logfiles in the program folder..
        /// </summary>
        internal static string PackingGroupCompleted2 {
            get {
                return ResourceManager.GetString("PackingGroupCompleted2", resourceCulture);
            }
        }
    }
}
